packages/commitlint-config/package.json

- release: commitlint-config v1.0.0

[RELEASE]: @commencis/commitlint-config@1.0.0

---

packages/stylelint-config/package.json

- release: stylelint-config v1.0.0

[RELEASE]: @commencis/stylelint-config@1.0.0

---

packages/eslint-plugin/package.json

- release: eslint-plugin v1.0.0

[RELEASE]: @commencis/eslint-plugin@1.0.0

---

packages/eslint-config/package.json

- release: eslint-config v1.0.0

[RELEASE]: @commencis/eslint-config@1.0.0

---

packages/eslint-config/src/configs/vue.ts
packages/eslint-config/src/plugins/vuePlugin.ts

- feat(eslint-config): add vue flat config

[FEATURE]: Add vue flat config

---

packages/eslint-config/package.json

- chore(eslint-config): update homepage url

[FEATURE]: Update homepage url

---

packages/eslint-config/package.json

- release: eslint-config v1.0.1

[RELEASE]: @commencis/eslint-config@1.0.1

---

packages/commitlint-config/package.json

- release: commitlint-config v1.0.1

[RELEASE]: @commencis/commitlint-config@1.0.1

---

packages/prettier-config/package.json

- release: prettier-config v1.0.1

[RELEASE]: @commencis/prettier-config@1.0.1

---

package.json
packages/eslint-config/README.md
packages/eslint-config/package.json
packages/eslint-config/src/configs/react-native.ts
packages/eslint-config/src/index.ts
packages/eslint-plugin/package.json
pnpm-lock.yaml

- Add React Native base config.
- Update typescript-eslint dependency in packages to latest
- Remove typescript-eslint dependency from root
- Update globals dependency

feat(eslint-config): add react-native config

---

renovate.json

- Add [Renovate](https://docs.renovatebot.com/) config.

chore(renovate): add initial renovate bot config

---

packages/stylelint-config/src/rules/cssRules.ts
packages/stylelint-config/src/rules/orderRules.ts
packages/stylelint-config/src/rules/scssRules.ts

- Update logical css attribute groups and orders
- Update color rules
- Update css variable rule exceptions

feat(stylelint-config): rule improvements

---

packages/stylelint-config/package.json

- release: @commencis/stylelint-config@1.1.0

release(stylelint-config): v1.1.0

---

packages/eslint-plugin/package.json

- release: @commencis/eslint-plugin@1.0.2

release(eslint-plugin): v1.0.2

---

packages/commitlint-config/package.json

- release: @commencis/commitlint-config@1.1.0

release(commitlint-config): v1.1.0

---

packages/stylelint-config/package.json

- release: stylelin-config@1.1.1

release(stylelint-config): v1.1.1

---

packages/prettier-config/package.json

- release: prettier-config@1.1.0

release(prettier-config): v1.1.0

---

.github/workflows/release.yaml

- change github token in release action

fix: github token in release action

---

.github/workflows/release.yaml

fix: checkout action

---

.changeset/neat-geckos-occur.md
packages/ts-config/package.json

- feat(ts-config): update package fields

feat(ts-config): update package fields

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

feat: update ci actions

---

.github/actions/setup/action.yaml

feat(ci): update setup action to use frozen-lockfile

feat(ci): update setup action to use frozen-lockfile

---

.changeset/hot-penguins-unite.md
packages/eslint-config/src/types/types.d.ts

feat(eslint-config): use eslint-plugin-vue types

feat(eslint-config): use eslint-plugin-vue types

---

renovate.json
shared/renovate/default.json

chore: convert renovate config to preset config

---

.changeset/config.json
package.json
pnpm-lock.yaml

chore: update changelog format

chore: update changelog format

---

.github/CODEOWNERS
README.md

feat: add codeowners & update readme

feat: add codeowners & update readme

---

.changeset/early-mugs-drop.md
packages/eslint-config/src/rules/importSortRules.ts

The goal of this PR is introduce new rules and enhance existing ones to handle more cases for sorting.

feat(eslint-config): introduce new import sorting rules

---

.changeset/dirty-mayflies-wink.md
packages/eslint-config/src/rules/importSortRules.ts

feat(eslint-config): re-arrange import groups

feat(eslint-config): re-arrange import groups

---

.changeset/beige-papayas-suffer.md

chore: add changeset for import sort updates

chore: add changeset for import sort updates

---

shared/renovate/default.json

feat(renovate): add node deps to config

feat(renovate): add node deps to config

---

package.json
pnpm-lock.yaml

chore(deps): update commencis deps

chore(deps): update commencis deps

---

shared/renovate/default.json

fix(renovate): update schedule for lock file maintenance job

fix(renovate): update schedule for lock file maintenance job

---

lint-staged.config.js
package.json
packages/lint-staged-config/LICENSE
packages/lint-staged-config/README.md
packages/lint-staged-config/package.json
packages/lint-staged-config/src/configs/base.ts
packages/lint-staged-config/src/configs/next.ts
packages/lint-staged-config/src/configs/react-native.ts
packages/lint-staged-config/src/configs/react.ts
packages/lint-staged-config/src/configs/typescript.ts
packages/lint-staged-config/src/configs/vue.ts
packages/lint-staged-config/src/constants/globs.ts
packages/lint-staged-config/src/constants/index.ts
packages/lint-staged-config/src/helpers/commands.ts
packages/lint-staged-config/src/helpers/index.ts
packages/lint-staged-config/src/index.ts
packages/lint-staged-config/tsconfig.json
packages/lint-staged-config/tsup.config.ts
pnpm-lock.yaml

feat: add lint-staged-config package

feat: add lint-staged-config package

---

.changeset/silly-rocks-lay.md
packages/stylelint-config/src/configs/styled.ts
packages/stylelint-config/src/rules/styledRules.ts

-  feat(stylelint): update styled-components config to resolve stylistic rule conflicts

feat: update styled-components config to resolve stylistic rule conflicts

---

.changeset/four-frogs-agree.md
packages/eslint-plugin/src/rules/copyright-text.ts
packages/eslint-plugin/src/utils/index.ts
packages/eslint-plugin/src/utils/validateCommencisCopyright.ts

feat(eslint-plugin): update copyright-text rule fixer for text replacement

feat(eslint-plugin): update copyright-text rule fixer for text replacement

---

.changeset/new-bags-kick.md
packages/eslint-plugin/src/rules/copyright-text.ts
packages/eslint-plugin/src/utils/validateCommencisCopyright.ts

fix(eslint-plugin): add vue support for copyright-text replacement

fix(eslint-plugin): add vue support for copyright-text replacement

---

.github/workflows/ci.yaml
package.json
packages/commitlint-config/package.json
packages/eslint-config/package.json
packages/eslint-plugin/package.json
packages/lint-staged-config/package.json
packages/prettier-config/package.json
packages/stylelint-config/package.json
pnpm-lock.yaml
tsconfig.json
turbo.json

- update typescript root dependency
- update tsconfig dependencies
- update ci-review
- optimize turbo scripts

feat: update typescript root dependency

---

.changeset/crazy-monkeys-boil.md
package.json
packages/eslint-config/src/rules/importSortRules.ts
pnpm-lock.yaml

fix(eslint-config): side-effect css imports

fix(eslint-config): side-effect css imports
